services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
networks:
  default:
    driver: bridge